import { Node, Edge } from "reactflow";
import { IVersion } from "../models/version";

// Spor Salonu Şablonu
export const gymTemplate: IVersion = {
  id: "gym",
  name: "Spor Salonu Şemaları",
  description: "Spor salonu yönetimi için temel veritabanı şemaları",
  is_active: false,
  type: "model",
  nodes: [
    {
      id: "user",
      position: { x: 100, y: 100 },
      data: {
        name: "User",
        description: "Kullanıcı bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "u1",
            name: "fullname",
            type: "string",
            label: "Adı Soyadı",
            validations: { required: true },
          },
          {
            id: "u2",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "u3",
            name: "password",
            type: "string",
            label: "Şifre",
            validations: { required: true },
          },
          {
            id: "u4",
            name: "role",
            type: "string",
            label: "Rol",
            validations: { required: true },
          },
        ],
      },
    },
    {
      id: "customer",
      position: { x: 100, y: 100 },
      data: {
        name: "Customer",
        description: "Müşteri bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "c2",
            name: "fullname",
            type: "string",
            label: "Adı Soyadı",
            validations: { required: true },
          },
          {
            id: "c3",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "c4",
            name: "phone",
            type: "string",
            label: "Telefon",
            validations: { required: true },
          },
          {
            id: "c6",
            name: "birthdate",
            type: "date",
            label: "Doğum Tarihi",
            validations: { required: true },
          },
          {
            id: "c7",
            name: "gender",
            type: "string",
            label: "Cinsiyet",
            validations: { required: true },
          },
          {
            id: "c8",
            name: "emergencyContact",
            type: "string",
            label: "Acil Durum ",
            validations: { required: false },
          },
          {
            id: "c9",
            name: "healthStatus",
            type: "string",
            label: "Sağlık Durumu",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "membership",
      position: { x: 500, y: 100 },
      data: {
        name: "Membership",
        description: "Üyelik bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "m2",
            name: "customer",
            type: "reference",
            label: "Müşteri",
            validations: { required: true },
          },
          {
            id: "m3",
            name: "startDate",
            type: "date",
            label: "Başlangıç Tarihi",
            validations: { required: true },
          },
          {
            id: "m4",
            name: "endDate",
            type: "date",
            label: "Bitiş Tarihi",
            validations: { required: true },
          },
          {
            id: "m5",
            name: "membershipType",
            type: "reference",
            label: "Üyelik Tipi",
            validations: { required: true },
          },
          {
            id: "m6",
            name: "status",
            type: "string",
            label: "Durum",
            validations: { required: true },
          },
        ],
      },
    },
    {
      id: "membershipType",
      position: { x: 900, y: 100 },
      data: {
        name: "MembershipType",
        description: "Üyelik paketlerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "mt2",
            name: "name",
            type: "string",
            label: "Adı",
            validations: { required: true },
          },
          {
            id: "mt3",
            name: "duration",
            type: "number",
            label: "Süre",
            validations: { required: true },
          },
          {
            id: "mt4",
            name: "price",
            type: "number",
            label: "Fiyat",
            validations: { required: true },
          },
          {
            id: "mt5",
            name: "description",
            type: "string",
            label: "Açıklama",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "trainer",
      position: { x: 100, y: 400 },
      data: {
        name: "Trainer",
        description: "Eğitmen bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "t2",
            name: "fullname",
            type: "string",
            label: "Adı Soyadı",
            validations: { required: true },
          },
          {
            id: "t3",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "t4",
            name: "phone",
            type: "string",
            label: "Telefon",
            validations: { required: true },
          },

          {
            id: "t8",
            name: "biography",
            type: "string",
            label: "Biyografi",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "activity",
      position: { x: 500, y: 400 },
      data: {
        name: "Activity",
        description: "Grup dersleri ve aktiviteleri içeren şema",
        isActive: true,
        fields: [
          {
            id: "a2",
            name: "title",
            type: "string",
            label: "Konu",
            validations: { required: true },
          },
          {
            id: "a3",
            name: "description",
            type: "string",
            label: "Açıklama",
            validations: { required: true },
          },
          {
            id: "a4",
            name: "capacity",
            type: "number",
            label: "Kapasite",
            validations: { required: true },
          },
          {
            id: "a5",
            name: "level",
            type: "string",
            label: "Seviye",
            validations: { required: true },
          },
          {
            id: "a6",
            name: "duration",
            type: "number",
            label: "Süre",
            validations: { required: true },
          },
          {
            id: "a7",
            name: "trainer",
            type: "reference",
            label: "Eğitmen",
            validations: { required: true },
          },
          {
            id: "a8",
            name: "startDate",
            type: "date",
            label: "Başlangıç",
            validations: { required: true },
          },
          {
            id: "a9",
            name: "endDate",
            type: "date",
            label: "Bitiş",
            validations: { required: true },
          },
          {
            id: "a10",
            name: "status",
            type: "string",
            label: "Durum",
            validations: { required: true },
          },
          {
            id: "a11",
            name: "notes",
            type: "string",
            label: "Notlar",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "participant",
      position: { x: 900, y: 400 },
      data: {
        name: "Participant",
        description: "Katılımcı bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "p2",
            name: "customer",
            type: "reference",
            label: "Müşteri",
            validations: { required: true },
          },
          {
            id: "p3",
            name: "activity",
            type: "reference",
            label: "Aktivite",
            validations: { required: true },
          },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "membership",
      target: "customer",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e2",
      source: "membership",
      target: "membershipType",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e3",
      source: "participant",
      target: "customer",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e4",
      source: "activity",
      target: "trainer",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e5",
      source: "customer",
      target: "user",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e6",
      source: "participant",
      target: "activity",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
  ],
};

// E-Ticaret Şablonu
const eCommerceTemplate: IVersion = {
  id: "e-commerce",
  name: "E-Ticaret Şemaları",
  description: "E-ticaret sistemi için temel veritabanı şemaları",
  is_active: true,
  type: "model",
  nodes: [
    {
      id: "product",
      position: { x: 100, y: 100 },
      data: {
        name: "Product",
        description: "Ürün bilgilerini içeren şema",
        isActive: true,
        fields: [
          { id: "p1", name: "id", type: "string", required: true },
          { id: "p2", name: "ad", type: "string", required: true },
          { id: "p3", name: "açıklama", type: "string", required: false },
          { id: "p4", name: "fiyat", type: "number", required: true },
          { id: "p5", name: "stok", type: "number", required: true },
          { id: "p6", name: "kategori", type: "reference", required: true },
          { id: "p7", name: "resimler", type: "array", required: false },
        ],
      },
    },
    {
      id: "category",
      position: { x: 500, y: 100 },
      data: {
        name: "Category",
        description: "Ürün kategorilerini içeren şema",
        isActive: true,
        fields: [
          { id: "c1", name: "id", type: "string", required: true },
          { id: "c2", name: "ad", type: "string", required: true },
          { id: "c3", name: "açıklama", type: "string", required: false },
          {
            id: "c4",
            name: "üstKategori",
            type: "reference",
            required: false,
          },
        ],
      },
    },
    {
      id: "customer",
      position: { x: 100, y: 400 },
      data: {
        name: "Customer",
        description: "Müşteri bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "u3",
            name: "fullname",
            type: "string",
            label: "Full Name",
            validations: { required: true },
          },
          {
            id: "u4",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "u5",
            name: "phone",
            type: "string",
            label: "Phone",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "order",
      position: { x: 500, y: 400 },
      data: {
        name: "Order",
        description: "Sipariş bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "o2",
            name: "customer",
            type: "reference",
            label: "Customer",
            validations: { required: true },
          },
          {
            id: "o3",
            name: "products",
            type: "array",
            label: "Products",
            validations: { required: true },
          },
          {
            id: "o4",
            name: "total",
            type: "number",
            label: "Total",
            validations: { required: true },
          },
          {
            id: "o5",
            name: "status",
            type: "string",
            label: "Status",
            validations: { required: true },
          },
          {
            id: "o6",
            name: "date",
            type: "date",
            label: "Date",
            validations: { required: true },
          },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "product",
      target: "category",

      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e2",
      source: "order",
      target: "customer",

      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e3",
      source: "order",
      target: "product",

      animated: true,
      label: "N:N",
      data: { relationType: "manyToMany" },
    },
  ],
};

// CRM Şablonu
const crmTemplate: IVersion = {
  id: "crm",
  name: "CRM Şemaları",
  description: "Müşteri ilişkileri yönetimi için temel veritabanı şemaları",
  is_active: false,
  type: "model",
  nodes: [
    {
      id: "User",
      position: { x: 100, y: 100 },
      data: {
        name: "User",
        description: "Müşteri ve potansiyel müşteri bilgilerini içeren şema",
        fields: [
          {
            id: "c1",
            name: "fullname",
            type: "string",
            label: "Full Name",
            validations: { required: true },
          },
          {
            id: "c2",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "c4",
            name: "role",
            type: "string",
            label: "Role",
            validations: { required: true },
          },
          {
            id: "c5",
            name: "password",
            type: "string",
            label: "Password",
            validations: { required: true },
          },
        ],
      },
    },
    {
      id: "Customer",
      position: { x: 500, y: 100 },
      data: {
        name: "Customer",
        description: "Customer bilgilerini içeren şema",
        fields: [
          {
            id: "co2",
            name: "fullname",
            type: "string",
            label: "Full Name",
            validations: { required: true },
          },
          {
            id: "co3",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "co4",
            name: "phone",
            type: "string",
            label: "Phone",
            validations: { required: false },
          },
          {
            id: "co5",
            name: "address",
            type: "object",
            label: "Address",
            validations: { required: false },
          },
          {
            id: "co6",
            name: "user",
            type: "reference",
            label: "User",
            validations: { required: true },
          },
        ],
      },
    },
    {
      id: "Activity",
      position: { x: 100, y: 400 },
      data: {
        name: "Activity",
        description: "Activity bilgilerini içeren şema",
        fields: [
          {
            id: "o2",
            name: "title",
            type: "string",
            label: "Title",
            validations: { required: true },
          },
          {
            id: "o3",
            name: "user",
            type: "reference",
            label: "User",
            validations: { required: true },
          },
          {
            id: "o4",
            name: "customer",
            type: "reference",
            label: "Customer",
            validations: { required: true },
          },
          {
            id: "o5",
            name: "status",
            type: "string",
            label: "Status",
            validations: { required: true },
          },
          {
            id: "o6",
            name: "description",
            type: "string",
            label: "Description",
            validations: { required: false },
          },
          {
            id: "o7",
            name: "date",
            type: "date",
            label: "Date",
            validations: { required: true },
          },
          {
            id: "o8",
            name: "type",
            type: "string",
            label: "Type",
            validations: { required: true },
          },
          {
            id: "o9",
            name: "priority",
            type: "string",
            label: "Priority",
            validations: { required: true },
          },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "Customer",
      target: "User",

      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e2",
      source: "Activity",
      target: "User",

      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e3",
      source: "Activity",
      target: "Customer",

      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
  ],
};

// İK Şablonu
const hrmTemplate: IVersion = {
  id: "hrm",
  name: "İK Şemaları",
  description: "İnsan kaynakları yönetimi için temel veritabanı şemaları",
  is_active: false,
  type: "model",
  nodes: [
    {
      id: "employee",
      position: { x: 100, y: 100 },
      data: {
        name: "Employee",
        description: "Çalışan bilgilerini içeren şema",
        fields: [
          { id: "e1", name: "id", type: "string", required: true },
          { id: "e2", name: "ad", type: "string", required: true },
          { id: "e3", name: "soyad", type: "string", required: true },
          { id: "e4", name: "email", type: "string", required: true },
          { id: "e5", name: "telefon", type: "string", required: false },
          { id: "e6", name: "departman", type: "reference", required: true },
          { id: "e7", name: "pozisyon", type: "reference", required: true },
          { id: "e8", name: "işeGiriş", type: "date", required: true },
        ],
      },
    },
    {
      id: "department",
      position: { x: 500, y: 100 },
      data: {
        name: "Department",
        description: "Departman bilgilerini içeren şema",
        fields: [
          { id: "d1", name: "id", type: "string", required: true },
          { id: "d2", name: "ad", type: "string", required: true },
          { id: "d3", name: "yönetici", type: "reference", required: false },
          { id: "d4", name: "açıklama", type: "string", required: false },
        ],
      },
    },
    {
      id: "position",
      position: { x: 100, y: 400 },
      data: {
        name: "Position",
        description: "Pozisyon bilgilerini içeren şema",
        fields: [
          { id: "p1", name: "id", type: "string", required: true },
          { id: "p2", name: "ad", type: "string", required: true },
          { id: "p3", name: "seviye", type: "string", required: true },
          { id: "p4", name: "departman", type: "reference", required: true },
        ],
      },
    },
    {
      id: "leave",
      position: { x: 500, y: 400 },
      data: {
        name: "Leave",
        description: "İzin kayıtlarını içeren şema",
        fields: [
          { id: "l1", name: "id", type: "string", required: true },
          { id: "l2", name: "çalışan", type: "reference", required: true },
          { id: "l3", name: "başlangıç", type: "date", required: true },
          { id: "l4", name: "bitiş", type: "date", required: true },
          { id: "l5", name: "tip", type: "string", required: true },
          { id: "l6", name: "durum", type: "string", required: true },
          { id: "l7", name: "açıklama", type: "string", required: false },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "employee",
      target: "department",

      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e2",
      source: "employee",
      target: "position",

      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e3",
      source: "position",
      target: "department",

      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e4",
      source: "leave",
      target: "employee",

      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
  ],
};

const investTrackerTemplate: IVersion = {
  id: "investTracker",
  name: "Invest Tracker",
  description: "Invest Tracker",
  is_active: false,
  type: "model",
  nodes: [
    {
      id: "investment",
      position: { x: 100, y: 100 },
      data: {
        name: "Investment",
        description: "Investment",
        fields: [
          { id: "i1", name: "id", type: "string", required: true },
          { id: "i2", name: "name", type: "string", required: true },
          { id: "i3", name: "amount", type: "number", required: true },
          { id: "i4", name: "date", type: "date", required: true },
          { id: "i5", name: "category", type: "reference", required: true },
          { id: "i6", name: "description", type: "string", required: false },
        ],
      },
    },
    {
      id: "category",
      position: { x: 500, y: 100 },
      data: {
        name: "Category",
        description: "Category",
        fields: [
          { id: "c1", name: "id", type: "string", required: true },
          { id: "c2", name: "name", type: "string", required: true },
          { id: "c3", name: "description", type: "string", required: false },
        ],
      },
    },
    {
      id: "user",
      position: { x: 100, y: 400 },
      data: {
        name: "User",
        description: "User",
        fields: [
          { id: "u1", name: "id", type: "string", required: true },
          { id: "u2", name: "name", type: "string", required: true },
          { id: "u3", name: "email", type: "string", required: true },
          { id: "u4", name: "password", type: "string", required: true },
          { id: "u5", name: "investments", type: "reference", required: false },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "investment",
      target: "category",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e2",
      source: "user",
      target: "investment",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
  ],
};

const matrixModelTemplate: IVersion = {
  id: "matrixModel",
  name: "Matrix Model",
  description: "Matrix Model",
  is_active: false,
  type: "model",
  nodes: [
    {
      id: "User",
      position: { x: 100, y: 100 },
      data: [
        {
          id: "n2",
          name: "fullname",
          type: "string",
          label: "Full Name",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "email",
          type: "string",
          label: "Email",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "password",
          type: "string",
          label: "Password",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "role",
          type: "string",
          label: "Role",
          validations: { required: true },
        },
        {
          id: "n6",
          name: "photo",
          type: "string",
          label: "Photo",
          validations: { required: false },
        },
      ],
    },
    {
      id: "Project",
      position: { x: 500, y: 100 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "n3",
          name: "user",
          type: "reference",
          label: "User",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Version",
      position: { x: 100, y: 400 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "n3",
          name: "is_active",
          type: "boolean",
          label: "Is Active",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "type",
          type: "string",
          label: "Type",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "project",
          type: "reference",
          label: "Project",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Node",
      position: { x: 500, y: 400 },
      data: [
        {
          id: "n1",
          name: "version",
          type: "reference",
          label: "Version",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "data",
          type: "object",
          label: "Data",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "position",
          type: "object",
          label: "Position",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Edge",
      position: { x: 100, y: 800 },
      data: [
        {
          id: "n1",
          name: "source",
          type: "string",
          label: "Source",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "target",
          type: "string",
          label: "Target",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "animated",
          type: "boolean",
          label: "Animated",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "label",
          type: "string",
          label: "Label",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "data",
          type: "object",
          label: "Data",
          validations: { required: true },
        },
        {
          id: "n6",
          name: "version",
          type: "reference",
          label: "Version",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Screen",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "n3",
          name: "props",
          type: "object",
          label: "Props",
          validations: { required: false },
        },
        {
          id: "n4",
          name: "project",
          type: "reference",
          label: "Project",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Page",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "n3",
          name: "props",
          type: "object",
          label: "Props",
          validations: { required: false },
        },
        {
          id: "n4",
          name: "project",
          type: "reference",
          label: "Project",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Flow",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "n3",
          name: "project",
          type: "reference",
          label: "Project",
          validations: { required: true },
        },
      ],
    },
    {
      id: "FlowStep",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "flow",
          type: "reference",
          label: "Flow",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "agent",
          type: "reference",
          label: "Agent",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "order",
          type: "number",
          label: "Order",
          validations: { required: true },
        },
      ],
    },
    {
      id: "FlowSession",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "flow",
          type: "reference",
          label: "Flow",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "session",
          type: "reference",
          label: "Session",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Agent",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "instructions",
          type: "string",
          label: "Instructions",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "stream",
          type: "boolean",
          label: "Stream",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "model_provider",
          type: "string",
          label: "Model Provider",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "model_name",
          type: "string",
          label: "Model Name",
          validations: { required: true },
        },
        {
          id: "n6",
          name: "key",
          type: "reference",
          label: "Key",
          validations: { required: true },
        },
        {
          id: "n7",
          name: "photo",
          type: "string",
          label: "Photo",
          validations: { required: false },
        },
        {
          id: "n8",
          name: "is_public",
          type: "boolean",
          label: "Is Public",
          validations: { required: true },
        },
        {
          id: "n9",
          name: "title",
          type: "string",
          label: "Title",
          validations: { required: false },
        },
        {
          id: "n10",
          name: "seed",
          type: "number",
          label: "Seed",
          validations: { required: true },
        },
        {
          id: "n11",
          name: "max_tokens",
          type: "number",
          label: "Max Tokens",
          validations: { required: true },
        },
        {
          id: "n12",
          name: "temperature",
          type: "number",
          label: "Temperature",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Key",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "value",
          type: "string",
          label: "Value",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "type",
          type: "string",
          label: "Type",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "user",
          type: "reference",
          label: "User",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
      ],
    },
    {
      id: "Hiring",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "user",
          type: "reference",
          label: "User",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "agent",
          type: "reference",
          label: "Agent",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Chat",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "role",
          type: "string",
          label: "Role",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "content",
          type: "string",
          label: "Content",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "session",
          type: "reference",
          label: "Session",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "attachments",
          type: "array",
          label: "Attachments",
          validations: { required: false },
        },
      ],
    },
    {
      id: "Session",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "agent",
          type: "reference",
          label: "Agent",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "user",
          type: "reference",
          label: "User",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Family",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "agent",
          type: "reference",
          label: "Agent",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "parent",
          type: "reference",
          label: "Parent",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Model",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "project",
          type: "reference",
          label: "Project",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
      ],
    },
    {
      id: "Field",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "model",
          type: "reference",
          label: "Model",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "label",
          type: "string",
          label: "Label",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "type",
          type: "string",
          label: "Type",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "validations",
          type: "object",
          label: "Validations",
          validations: { required: false },
        },
      ],
    },
  ],
  edges: [
    {
      id: "e1",
      source: "Key",
      target: "Agent",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e2",
      source: "Session",
      target: "Chat",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e3",
      source: "Version",
      target: "Edge",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e4",
      source: "Family",
      target: "Agent",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e5",
      source: "Model",
      target: "Field",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e6",
      source: "Project",
      target: "Flow",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e7",
      source: "Flow",
      target: "FlowSession",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e8",
      source: "Session",
      target: "FlowSession",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e9",
      source: "Agent",
      target: "FlowStep",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e10",
      source: "Flow",
      target: "FlowStep",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e11",
      source: "User",
      target: "Hiring",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e12",
      source: "Agent",
      target: "Hiring",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e13",
      source: "User",
      target: "Key",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e14",
      source: "Project",
      target: "Model",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e15",
      source: "Version",
      target: "Node",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e16",
      source: "Project",
      target: "Page",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e17",
      source: "User",
      target: "Project",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e18",
      source: "Project",
      target: "Screen",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e19",
      source: "Agent",
      target: "Session",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e20",
      source: "User",
      target: "Session",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e21",
      source: "Project",
      target: "Version",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
  ],
};

export const templates: IVersion[] = [
  eCommerceTemplate,
  crmTemplate,
  hrmTemplate,
  gymTemplate,
  investTrackerTemplate,
  matrixModelTemplate,
];

export const defaultNodes: Node[] = eCommerceTemplate.nodes;
export const defaultEdges: Edge[] = eCommerceTemplate.edges;
