import { Node, Edge } from "reactflow";
import { IVersion } from "../models/version";

// Spor Salonu Şablonu
export const gymTemplate: IVersion = {
  id: "gym",
  name: "Spor Salonu Şemaları",
  description: "Spor salonu yönetimi için temel veritabanı şemaları",
  is_active: false,
  models: [
    {
      name: "User",
      fields: [
        {
          name: "fullname",
          type: "string",
          label: "Adı Soyadı",
        },
        {
          name: "email",
          type: "string",
          label: "Email",
        },
        {
          name: "password",
          type: "string",
          label: "Şifre",
        },
        {
          name: "role",
          type: "string",
          label: "Rol",
        },
      ],
    },
    {
      name: "Customer",
      fields: [
        {
          name: "fullname",
          type: "string",
          label: "Adı Soyadı",
        },

        {
          name: "email",
          type: "string",
          label: "Email",
        },
        {
          name: "phone",
          type: "string",
          label: "Telefon",
        },
      ],
    },
    {
      name: "Membership",
      fields: [
        {
          name: "customer",
          type: "reference",
          label: "Müşteri",
        },
        {
          name: "startDate",
          type: "date",
          label: "Başlangıç Tarihi",
        },
        {
          name: "endDate",
          type: "date",
          label: "Bitiş Tarihi",
        },
        {
          name: "membershipType",
          type: "reference",
          label: "Üyelik Tipi",
        },
        {
          name: "status",
          type: "string",
          label: "Durum",
        },
      ],
    },
    {
      name: "MembershipType",
      fields: [
        {
          name: "name",
          type: "string",
          label: "Adı",
        },
        {
          name: "duration",
          type: "number",
          label: "Süre",
        },
        {
          name: "price",
          type: "number",
          label: "Fiyat",
        },
        {
          name: "description",
          type: "string",
          label: "Açıklama",
        },
      ],
    },
    {
      name: "Trainer",
      fields: [
        {
          name: "fullname",
          type: "string",
          label: "Adı Soyadı",
        },
        {
          name: "email",
          type: "string",
          label: "Email",
        },
        {
          name: "phone",
          type: "string",
          label: "Telefon",
        },
        {
          name: "biography",
          type: "string",
          label: "Biyografi",
        },
      ],
    },
    {
      name: "Activity",
      fields: [
        {
          name: "name",
          type: "string",
          label: "Adı",
        },
        {
          name: "açıklama",
          type: "string",
          label: "Açıklama",
        },
        {
          name: "capacity",
          type: "number",
          label: "Kapasite",
        },
        {
          name: "level",
          type: "string",
          label: "Seviye",
        },
        {
          name: "duration",
          type: "number",
          label: "Süre",
        },
      ],
    },
    {
      name: "Schedule",
      fields: [
        {
          name: "activity",
          type: "reference",
          label: "Aktivite",
        },
        {
          name: "trainer",
          type: "reference",
          label: "Eğitmen",
        },
        {
          name: "startDate",
          type: "date",
          label: "Başlangıç Tarihi",
        },
        {
          name: "endDate",
          type: "date",
          label: "Bitiş Tarihi",
        },
        {
          name: "participants",
          type: "array",
          label: "Katılımcılar",
        },
        {
          name: "status",
          type: "string",
          label: "Durum",
        },
        {
          name: "notes",
          type: "string",
          label: "Notlar",
        },
      ],
    },
  ],
  nodes: [
    {
      id: "user",
      type: "schema",
      position: { x: 100, y: 100 },
      data: {
        name: "User",
        description: "Kullanıcı bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "u1",
            name: "fullname",
            type: "string",
            label: "Adı Soyadı",
            validations: { required: true },
          },
          {
            id: "u2",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "u3",
            name: "password",
            type: "string",
            label: "Şifre",
            validations: { required: true },
          },
          {
            id: "u4",
            name: "role",
            type: "string",
            label: "Rol",
            validations: { required: true },
          },
        ],
      },
    },
    {
      id: "customer",
      type: "schema",
      position: { x: 100, y: 100 },
      data: {
        name: "Customer",
        description: "Müşteri bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "c2",
            name: "fullname",
            type: "string",
            label: "Adı Soyadı",
            validations: { required: true },
          },
          {
            id: "c3",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "c4",
            name: "phone",
            type: "string",
            label: "Telefon",
            validations: { required: true },
          },
          {
            id: "c6",
            name: "birthdate",
            type: "date",
            label: "Doğum Tarihi",
            validations: { required: true },
          },
          {
            id: "c7",
            name: "gender",
            type: "string",
            label: "Cinsiyet",
            validations: { required: true },
          },
          {
            id: "c8",
            name: "emergencyContact",
            type: "string",
            label: "Acil Durum ",
            validations: { required: false },
          },
          {
            id: "c9",
            name: "healthStatus",
            type: "string",
            label: "Sağlık Durumu",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "membership",
      type: "schema",
      position: { x: 500, y: 100 },
      data: {
        name: "Membership",
        description: "Üyelik bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "m2",
            name: "customer",
            type: "reference",
            label: "Müşteri",
            validations: { required: true },
          },
          {
            id: "m3",
            name: "startDate",
            type: "date",
            label: "Başlangıç Tarihi",
            validations: { required: true },
          },
          {
            id: "m4",
            name: "endDate",
            type: "date",
            label: "Bitiş Tarihi",
            validations: { required: true },
          },
          {
            id: "m5",
            name: "membershipType",
            type: "reference",
            label: "Üyelik Tipi",
            validations: { required: true },
          },
          {
            id: "m6",
            name: "status",
            type: "string",
            label: "Durum",
            validations: { required: true },
          },
        ],
      },
    },
    {
      id: "membershipType",
      type: "schema",
      position: { x: 900, y: 100 },
      data: {
        name: "MembershipType",
        description: "Üyelik paketlerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "mt2",
            name: "name",
            type: "string",
            label: "Adı",
            validations: { required: true },
          },
          {
            id: "mt3",
            name: "duration",
            type: "number",
            label: "Süre",
            validations: { required: true },
          },
          {
            id: "mt4",
            name: "price",
            type: "number",
            label: "Fiyat",
            validations: { required: true },
          },
          {
            id: "mt5",
            name: "description",
            type: "string",
            label: "Açıklama",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "trainer",
      type: "schema",
      position: { x: 100, y: 400 },
      data: {
        name: "Trainer",
        description: "Eğitmen bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "t2",
            name: "fullname",
            type: "string",
            label: "Adı Soyadı",
            validations: { required: true },
          },
          {
            id: "t3",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "t4",
            name: "phone",
            type: "string",
            label: "Telefon",
            validations: { required: true },
          },

          {
            id: "t8",
            name: "biography",
            type: "string",
            label: "Biyografi",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "activity",
      type: "schema",
      position: { x: 500, y: 400 },
      data: {
        name: "Activity",
        description: "Grup dersleri ve aktiviteleri içeren şema",
        isActive: true,
        fields: [
          {
            id: "a2",
            name: "title",
            type: "string",
            label: "Konu",
            validations: { required: true },
          },
          {
            id: "a3",
            name: "description",
            type: "string",
            label: "Açıklama",
            validations: { required: true },
          },
          {
            id: "a4",
            name: "capacity",
            type: "number",
            label: "Kapasite",
            validations: { required: true },
          },
          {
            id: "a5",
            name: "level",
            type: "string",
            label: "Seviye",
            validations: { required: true },
          },
          {
            id: "a6",
            name: "duration",
            type: "number",
            label: "Süre",
            validations: { required: true },
          },
          {
            id: "a7",
            name: "trainer",
            type: "reference",
            label: "Eğitmen",
            validations: { required: true },
          },
          {
            id: "a8",
            name: "startDate",
            type: "date",
            label: "Başlangıç",
            validations: { required: true },
          },
          {
            id: "a9",
            name: "endDate",
            type: "date",
            label: "Bitiş",
            validations: { required: true },
          },
          {
            id: "a10",
            name: "status",
            type: "string",
            label: "Durum",
            validations: { required: true },
          },
          {
            id: "a11",
            name: "notes",
            type: "string",
            label: "Notlar",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "participant",
      type: "schema",
      position: { x: 900, y: 400 },
      data: {
        name: "Participant",
        description: "Katılımcı bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "p2",
            name: "customer",
            type: "reference",
            label: "Müşteri",
            validations: { required: true },
          },
          {
            id: "p3",
            name: "activity",
            type: "reference",
            label: "Aktivite",
            validations: { required: true },
          },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "membership",
      target: "customer",
      sourceName: "Membership",
      targetName: "Customer",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e2",
      source: "membership",
      target: "membershipType",
      sourceName: "Membership",
      targetName: "MembershipType",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e3",
      source: "participant",
      target: "customer",
      sourceName: "Participant",
      targetName: "Customer",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e4",
      source: "activity",
      target: "trainer",
      sourceName: "Activity",
      targetName: "Trainer",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e5",
      source: "customer",
      target: "user",
      sourceName: "Customer",
      targetName: "User",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e6",
      source: "participant",
      target: "activity",
      sourceName: "Participant",
      targetName: "Activity",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
  ],
};

// E-Ticaret Şablonu
const eCommerceTemplate: IVersion = {
  id: "e-commerce",
  name: "E-Ticaret Şemaları",
  description: "E-ticaret sistemi için temel veritabanı şemaları",
  is_active: true,
  models: [
    {
      name: "Product",
      fields: [
        {
          id: "p2",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "p3",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "p4",
          name: "price",
          type: "number",
          label: "Price",
          validations: { required: true },
        },
        {
          id: "p5",
          name: "stock",
          type: "number",
          label: "Stock",
          validations: { required: true },
        },
        {
          id: "p6",
          name: "category",
          type: "reference",
          label: "Category",
          validations: { required: true },
        },
        {
          id: "p7",
          name: "images",
          type: "array",
          label: "Images",
          validations: { required: false },
        },
      ],
    },
    {
      name: "Category",
      fields: [
        {
          id: "c2",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "c3",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "c4",
          name: "parent",
          type: "reference",
          label: "Parent",
          validations: { required: false },
        },
      ],
    },
    {
      name: "Customer",
      fields: [
        {
          id: "u1",
          name: "fullname",
          type: "string",
          label: "Full Name",
          validations: { required: true },
        },
        {
          id: "u2",
          name: "email",
          type: "string",
          label: "Email",
          validations: { required: true },
        },
        {
          id: "u3",
          name: "phone",
          type: "string",
          label: "Phone",
          validations: { required: false },
        },
      ],
    },
    {
      name: "Order",
      fields: [
        {
          id: "o1",
          name: "customer",
          type: "reference",
          label: "Customer",
          validations: { required: true },
        },
        {
          id: "o2",
          name: "products",
          type: "array",
          label: "Products",
          validations: { required: true },
        },
        {
          id: "o3",
          name: "total",
          type: "number",
          label: "Total",
          validations: { required: true },
        },
        {
          id: "o4",
          name: "status",
          type: "string",
          label: "Status",
          validations: { required: true },
        },
        {
          id: "o5",
          name: "date",
          type: "date",
          label: "Date",
          validations: { required: true },
        },
      ],
    },
  ],
  nodes: [
    {
      id: "product",
      type: "schema",
      position: { x: 100, y: 100 },
      data: {
        name: "Product",
        description: "Ürün bilgilerini içeren şema",
        isActive: true,
        fields: [
          { id: "p1", name: "id", type: "string", required: true },
          { id: "p2", name: "ad", type: "string", required: true },
          { id: "p3", name: "açıklama", type: "string", required: false },
          { id: "p4", name: "fiyat", type: "number", required: true },
          { id: "p5", name: "stok", type: "number", required: true },
          { id: "p6", name: "kategori", type: "reference", required: true },
          { id: "p7", name: "resimler", type: "array", required: false },
        ],
      },
    },
    {
      id: "category",
      type: "schema",
      position: { x: 500, y: 100 },
      data: {
        name: "Category",
        description: "Ürün kategorilerini içeren şema",
        isActive: true,
        fields: [
          { id: "c1", name: "id", type: "string", required: true },
          { id: "c2", name: "ad", type: "string", required: true },
          { id: "c3", name: "açıklama", type: "string", required: false },
          {
            id: "c4",
            name: "üstKategori",
            type: "reference",
            required: false,
          },
        ],
      },
    },
    {
      id: "customer",
      type: "schema",
      position: { x: 100, y: 400 },
      data: {
        name: "Customer",
        description: "Müşteri bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "u3",
            name: "fullname",
            type: "string",
            label: "Full Name",
            validations: { required: true },
          },
          {
            id: "u4",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "u5",
            name: "phone",
            type: "string",
            label: "Phone",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "order",
      type: "schema",
      position: { x: 500, y: 400 },
      data: {
        name: "Order",
        description: "Sipariş bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "o2",
            name: "customer",
            type: "reference",
            label: "Customer",
            validations: { required: true },
          },
          {
            id: "o3",
            name: "products",
            type: "array",
            label: "Products",
            validations: { required: true },
          },
          {
            id: "o4",
            name: "total",
            type: "number",
            label: "Total",
            validations: { required: true },
          },
          {
            id: "o5",
            name: "status",
            type: "string",
            label: "Status",
            validations: { required: true },
          },
          {
            id: "o6",
            name: "date",
            type: "date",
            label: "Date",
            validations: { required: true },
          },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "product",
      target: "category",
      sourceName: "product",
      targetName: "category",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e2",
      source: "order",
      target: "customer",
      sourceName: "order",
      targetName: "customer",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e3",
      source: "order",
      target: "product",
      sourceName: "order",
      targetName: "product",
      animated: true,
      label: "N:N",
      data: { relationType: "manyToMany" },
    },
  ],
};

// CRM Şablonu
const crmTemplate: IVersion = {
  id: "crm",
  name: "CRM Şemaları",
  description: "Müşteri ilişkileri yönetimi için temel veritabanı şemaları",
  is_active: false,
  models: [
    {
      name: "User",
      fields: [
        {
          id: "c1",
          name: "fullname",
          type: "string",
          label: "Full Name",
          validations: { required: true },
        },
        {
          id: "c2",
          name: "email",
          type: "string",
          label: "Email",
          validations: { required: true },
        },
        {
          id: "c4",
          name: "role",
          type: "string",
          label: "Role",
          validations: { required: true },
        },
        {
          id: "c5",
          name: "password",
          type: "string",
          label: "Password",
          validations: { required: true },
        },
      ],
    },
    {
      name: "Customer",
      fields: [
        {
          id: "co2",
          name: "fullname",
          type: "string",
          label: "Full Name",
          validations: { required: true },
        },
        {
          id: "co3",
          name: "email",
          type: "string",
          label: "Email",
          validations: { required: true },
        },
        {
          id: "co4",
          name: "phone",
          type: "string",
          label: "Phone",
          validations: { required: false },
        },
        {
          id: "co5",
          name: "address",
          type: "object",
          label: "Address",
          validations: { required: false },
        },
        {
          id: "co6",
          name: "user",
          type: "reference",
          label: "User",
          validations: { required: true },
        },
      ],
    },
    {
      name: "Activity",
      fields: [
        {
          id: "o2",
          name: "title",
          type: "string",
          label: "Title",
          validations: { required: true },
        },
        {
          id: "o3",
          name: "user",
          type: "reference",
          label: "User",
          validations: { required: true },
        },
        {
          id: "o4",
          name: "customer",
          type: "reference",
          label: "Customer",
          validations: { required: true },
        },
        {
          id: "o5",
          name: "status",
          type: "string",
          label: "Status",
          validations: { required: true },
        },
        {
          id: "o6",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "o7",
          name: "date",
          type: "date",
          label: "Date",
          validations: { required: true },
        },
        {
          id: "o8",
          name: "type",
          type: "string",
          label: "Type",
          validations: { required: true },
        },
        {
          id: "o9",
          name: "priority",
          type: "string",
          label: "Priority",
          validations: { required: true },
        },
      ],
    },
  ],
  nodes: [
    {
      id: "User",
      type: "schema",
      position: { x: 100, y: 100 },
      data: {
        name: "User",
        description: "Müşteri ve potansiyel müşteri bilgilerini içeren şema",
        fields: [
          {
            id: "c1",
            name: "fullname",
            type: "string",
            label: "Full Name",
            validations: { required: true },
          },
          {
            id: "c2",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "c4",
            name: "role",
            type: "string",
            label: "Role",
            validations: { required: true },
          },
          {
            id: "c5",
            name: "password",
            type: "string",
            label: "Password",
            validations: { required: true },
          },
        ],
      },
    },
    {
      id: "Customer",
      type: "schema",
      position: { x: 500, y: 100 },
      data: {
        name: "Customer",
        description: "Customer bilgilerini içeren şema",
        fields: [
          {
            id: "co2",
            name: "fullname",
            type: "string",
            label: "Full Name",
            validations: { required: true },
          },
          {
            id: "co3",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "co4",
            name: "phone",
            type: "string",
            label: "Phone",
            validations: { required: false },
          },
          {
            id: "co5",
            name: "address",
            type: "object",
            label: "Address",
            validations: { required: false },
          },
          {
            id: "co6",
            name: "user",
            type: "reference",
            label: "User",
            validations: { required: true },
          },
        ],
      },
    },
    {
      id: "Activity",
      type: "schema",
      position: { x: 100, y: 400 },
      data: {
        name: "Activity",
        description: "Activity bilgilerini içeren şema",
        fields: [
          {
            id: "o2",
            name: "title",
            type: "string",
            label: "Title",
            validations: { required: true },
          },
          {
            id: "o3",
            name: "user",
            type: "reference",
            label: "User",
            validations: { required: true },
          },
          {
            id: "o4",
            name: "customer",
            type: "reference",
            label: "Customer",
            validations: { required: true },
          },
          {
            id: "o5",
            name: "status",
            type: "string",
            label: "Status",
            validations: { required: true },
          },
          {
            id: "o6",
            name: "description",
            type: "string",
            label: "Description",
            validations: { required: false },
          },
          {
            id: "o7",
            name: "date",
            type: "date",
            label: "Date",
            validations: { required: true },
          },
          {
            id: "o8",
            name: "type",
            type: "string",
            label: "Type",
            validations: { required: true },
          },
          {
            id: "o9",
            name: "priority",
            type: "string",
            label: "Priority",
            validations: { required: true },
          },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "Customer",
      target: "User",
      sourceName: "Customer",
      targetName: "User",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e2",
      source: "Activity",
      target: "User",
      sourceName: "Activity",
      targetName: "User",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e3",
      source: "Activity",
      target: "Customer",
      sourceName: "Activity",
      targetName: "Customer",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
  ],
};

// İK Şablonu
const hrmTemplate: IVersion = {
  id: "hrm",
  name: "İK Şemaları",
  description: "İnsan kaynakları yönetimi için temel veritabanı şemaları",
  is_active: false,
  models: [
    {
      name: "Employee",
      fields: [
        {
          id: "e2",
          name: "ad",
          type: "string",
          label: "Ad",
          validations: { required: true },
        },
        {
          id: "e3",
          name: "soyad",
          type: "string",
          label: "Soyad",
          validations: { required: true },
        },
        {
          id: "e4",
          name: "email",
          type: "string",
          label: "Email",
          validations: { required: true },
        },
        {
          id: "e5",
          name: "telefon",
          type: "string",
          label: "Telefon",
          validations: { required: false },
        },
        {
          id: "e6",
          name: "departman",
          type: "reference",
          label: "Departman",
          validations: { required: true },
        },
        {
          id: "e7",
          name: "pozisyon",
          type: "reference",
          label: "Pozisyon",
          validations: { required: true },
        },
        {
          id: "e8",
          name: "işeGiriş",
          type: "date",
          label: "İşe Giriş",
          validations: { required: true },
        },
      ],
    },
    {
      name: "Department",
      fields: [
        {
          id: "d2",
          name: "ad",
          type: "string",
          label: "Ad",
          validations: { required: true },
        },
        {
          id: "d3",
          name: "yönetici",
          type: "reference",
          label: "Yönetici",
          validations: { required: false },
        },
        {
          id: "d4",
          name: "açıklama",
          type: "string",
          label: "Açıklama",
          validations: { required: false },
        },
      ],
    },
    {
      name: "Position",
      fields: [
        {
          id: "p2",
          name: "ad",
          type: "string",
          label: "Ad",
          validations: { required: true },
        },
        {
          id: "p3",
          name: "seviye",
          type: "string",
          label: "Seviye",
          validations: { required: true },
        },
        {
          id: "p4",
          name: "departman",
          type: "reference",
          label: "Departman",
          validations: { required: true },
        },
      ],
    },
    {
      name: "Leave",
      fields: [
        {
          id: "l2",
          name: "çalışan",
          type: "reference",
          label: "Çalışan",
          validations: { required: true },
        },
        {
          id: "l3",
          name: "başlangıç",
          type: "date",
          label: "Başlangıç",
          validations: { required: true },
        },
        {
          id: "l4",
          name: "bitiş",
          type: "date",
          label: "Bitiş",
          validations: { required: true },
        },
        {
          id: "l5",
          name: "tip",
          type: "string",
          label: "Tip",
          validations: { required: true },
        },
        {
          id: "l6",
          name: "durum",
          type: "string",
          label: "Durum",
          validations: { required: true },
        },
        {
          id: "l7",
          name: "açıklama",
          type: "string",
          label: "Açıklama",
          validations: { required: false },
        },
      ],
    },
  ],
  nodes: [
    {
      id: "employee",
      type: "schema",
      position: { x: 100, y: 100 },
      data: {
        name: "Employee",
        description: "Çalışan bilgilerini içeren şema",
        fields: [
          { id: "e1", name: "id", type: "string", required: true },
          { id: "e2", name: "ad", type: "string", required: true },
          { id: "e3", name: "soyad", type: "string", required: true },
          { id: "e4", name: "email", type: "string", required: true },
          { id: "e5", name: "telefon", type: "string", required: false },
          { id: "e6", name: "departman", type: "reference", required: true },
          { id: "e7", name: "pozisyon", type: "reference", required: true },
          { id: "e8", name: "işeGiriş", type: "date", required: true },
        ],
      },
    },
    {
      id: "department",
      type: "schema",
      position: { x: 500, y: 100 },
      data: {
        name: "Department",
        description: "Departman bilgilerini içeren şema",
        fields: [
          { id: "d1", name: "id", type: "string", required: true },
          { id: "d2", name: "ad", type: "string", required: true },
          { id: "d3", name: "yönetici", type: "reference", required: false },
          { id: "d4", name: "açıklama", type: "string", required: false },
        ],
      },
    },
    {
      id: "position",
      type: "schema",
      position: { x: 100, y: 400 },
      data: {
        name: "Position",
        description: "Pozisyon bilgilerini içeren şema",
        fields: [
          { id: "p1", name: "id", type: "string", required: true },
          { id: "p2", name: "ad", type: "string", required: true },
          { id: "p3", name: "seviye", type: "string", required: true },
          { id: "p4", name: "departman", type: "reference", required: true },
        ],
      },
    },
    {
      id: "leave",
      type: "schema",
      position: { x: 500, y: 400 },
      data: {
        name: "Leave",
        description: "İzin kayıtlarını içeren şema",
        fields: [
          { id: "l1", name: "id", type: "string", required: true },
          { id: "l2", name: "çalışan", type: "reference", required: true },
          { id: "l3", name: "başlangıç", type: "date", required: true },
          { id: "l4", name: "bitiş", type: "date", required: true },
          { id: "l5", name: "tip", type: "string", required: true },
          { id: "l6", name: "durum", type: "string", required: true },
          { id: "l7", name: "açıklama", type: "string", required: false },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "employee",
      target: "department",
      sourceName: "employee",
      targetName: "department",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e2",
      source: "employee",
      target: "position",
      sourceName: "employee",
      targetName: "position",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e3",
      source: "position",
      target: "department",
      sourceName: "position",
      targetName: "department",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e4",
      source: "leave",
      target: "employee",
      sourceName: "leave",
      targetName: "employee",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
  ],
};

const investTrackerTemplate: IVersion = {
  id: "investTracker",
  name: "Invest Tracker",
  description: "Invest Tracker",
  is_active: false,
  models: [
    {
      name: "Investment",
      fields: [
        {
          id: "i1",
          name: "id",
          type: "string",
          label: "ID",
          validations: { required: true },
        },
        {
          id: "i2",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "i3",
          name: "amount",
          type: "number",
          label: "Amount",
          validations: { required: true },
        },
        {
          id: "i4",
          name: "date",
          type: "date",
          label: "Date",
          validations: { required: true },
        },
        {
          id: "i5",
          name: "category",
          type: "string",
          label: "Category",
          validations: { required: true },
        },
        {
          id: "i6",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
      ],
    },
    {
      name: "Category",
      fields: [
        {
          id: "c1",
          name: "id",
          type: "string",
          label: "ID",
          validations: { required: true },
        },
        {
          id: "c2",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "c3",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
      ],
    },
    {
      name: "User",
      fields: [
        {
          id: "u1",
          name: "id",
          type: "string",
          label: "ID",
          validations: { required: true },
        },
        {
          id: "u2",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "u3",
          name: "email",
          type: "string",
          label: "Email",
          validations: { required: true },
        },
        {
          id: "u4",
          name: "password",
          type: "string",
          label: "Password",
          validations: { required: true },
        },
        {
          id: "u5",
          name: "investments",
          type: "reference",
          label: "Investments",
          validations: { required: false },
        },
      ],
    },
  ],
  nodes: [
    {
      id: "investment",
      type: "schema",
      position: { x: 100, y: 100 },
      data: {
        name: "Investment",
        description: "Investment",
        fields: [
          { id: "i1", name: "id", type: "string", required: true },
          { id: "i2", name: "name", type: "string", required: true },
          { id: "i3", name: "amount", type: "number", required: true },
          { id: "i4", name: "date", type: "date", required: true },
          { id: "i5", name: "category", type: "reference", required: true },
          { id: "i6", name: "description", type: "string", required: false },
        ],
      },
    },
    {
      id: "category",
      type: "schema",
      position: { x: 500, y: 100 },
      data: {
        name: "Category",
        description: "Category",
        fields: [
          { id: "c1", name: "id", type: "string", required: true },
          { id: "c2", name: "name", type: "string", required: true },
          { id: "c3", name: "description", type: "string", required: false },
        ],
      },
    },
    {
      id: "user",
      type: "schema",
      position: { x: 100, y: 400 },
      data: {
        name: "User",
        description: "User",
        fields: [
          { id: "u1", name: "id", type: "string", required: true },
          { id: "u2", name: "name", type: "string", required: true },
          { id: "u3", name: "email", type: "string", required: true },
          { id: "u4", name: "password", type: "string", required: true },
          { id: "u5", name: "investments", type: "reference", required: false },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "investment",
      target: "category",
      sourceName: "investment",
      targetName: "category",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
    {
      id: "e2",
      source: "user",
      target: "investment",
      sourceName: "user",
      targetName: "investment",
      animated: true,
      label: "N:1",
      data: { relationType: "oneToMany" },
    },
  ],
};

export const templates: IVersion[] = [
  eCommerceTemplate,
  crmTemplate,
  hrmTemplate,
  gymTemplate,
  investTrackerTemplate,
];

export const defaultNodes: Node[] = eCommerceTemplate.nodes;
export const defaultEdges: Edge[] = eCommerceTemplate.edges;
