import { IVersion, VersionType } from "@/lib/models/version";

// Spor Salonu Şablonu
export const gymModel: IVersion<VersionType.MODEL> = {
  id: "gym",
  name: "Spor Salonu",
  description: "Spor salonu yönetimi için temel veritabanı şemaları",
  is_active: false,
  type: VersionType.MODEL,
  nodes: [
    {
      id: "user",
      position: { x: 100, y: 100 },
      type: VersionType.MODEL,
      data: {
        name: "User",
        description: "Kullanıcı bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "u1",
            name: "fullname",
            type: "string",
            label: "Adı Soyadı",
            validations: { required: true },
          },
          {
            id: "u2",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "u3",
            name: "password",
            type: "string",
            label: "Şifre",
            validations: { required: true },
          },
          {
            id: "u4",
            name: "role",
            type: "string",
            label: "Rol",
            validations: { required: true },
          },
        ],
      },
    },
    {
      id: "customer",
      position: { x: 100, y: 100 },
      type: VersionType.MODEL,
      data: {
        name: "Customer",
        description: "Müşteri bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "c2",
            name: "fullname",
            type: "string",
            label: "Adı Soyadı",
            validations: { required: true },
          },
          {
            id: "c3",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "c4",
            name: "phone",
            type: "string",
            label: "Telefon",
            validations: { required: true },
          },
          {
            id: "c6",
            name: "birthdate",
            type: "date",
            label: "Doğum Tarihi",
            validations: { required: true },
          },
          {
            id: "c7",
            name: "gender",
            type: "string",
            label: "Cinsiyet",
            validations: { required: true },
          },
          {
            id: "c8",
            name: "emergencyContact",
            type: "string",
            label: "Acil Durum ",
            validations: { required: false },
          },
          {
            id: "c9",
            name: "healthStatus",
            type: "string",
            label: "Sağlık Durumu",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "membership",
      position: { x: 500, y: 100 },
      type: VersionType.MODEL,
      data: {
        name: "Membership",
        description: "Üyelik bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "m2",
            name: "customer",
            type: "reference",
            label: "Müşteri",
            validations: { required: true },
          },
          {
            id: "m3",
            name: "startDate",
            type: "date",
            label: "Başlangıç Tarihi",
            validations: { required: true },
          },
          {
            id: "m4",
            name: "endDate",
            type: "date",
            label: "Bitiş Tarihi",
            validations: { required: true },
          },
          {
            id: "m5",
            name: "membershipType",
            type: "reference",
            label: "Üyelik Tipi",
            validations: { required: true },
          },
          {
            id: "m6",
            name: "status",
            type: "string",
            label: "Durum",
            validations: { required: true },
          },
        ],
      },
    },
    {
      id: "membershipType",
      position: { x: 900, y: 100 },
      type: VersionType.MODEL,
      data: {
        name: "MembershipType",
        description: "Üyelik paketlerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "mt2",
            name: "name",
            type: "string",
            label: "Adı",
            validations: { required: true },
          },
          {
            id: "mt3",
            name: "duration",
            type: "number",
            label: "Süre",
            validations: { required: true },
          },
          {
            id: "mt4",
            name: "price",
            type: "number",
            label: "Fiyat",
            validations: { required: true },
          },
          {
            id: "mt5",
            name: "description",
            type: "string",
            label: "Açıklama",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "trainer",
      position: { x: 100, y: 400 },
      type: VersionType.MODEL,
      data: {
        name: "Trainer",
        description: "Eğitmen bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "t2",
            name: "fullname",
            type: "string",
            label: "Adı Soyadı",
            validations: { required: true },
          },
          {
            id: "t3",
            name: "email",
            type: "string",
            label: "Email",
            validations: { required: true },
          },
          {
            id: "t4",
            name: "phone",
            type: "string",
            label: "Telefon",
            validations: { required: true },
          },

          {
            id: "t8",
            name: "biography",
            type: "string",
            label: "Biyografi",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "activity",
      position: { x: 500, y: 400 },
      type: VersionType.MODEL,
      data: {
        name: "Activity",
        description: "Grup dersleri ve aktiviteleri içeren şema",
        isActive: true,
        fields: [
          {
            id: "a2",
            name: "title",
            type: "string",
            label: "Konu",
            validations: { required: true },
          },
          {
            id: "a3",
            name: "description",
            type: "string",
            label: "Açıklama",
            validations: { required: true },
          },
          {
            id: "a4",
            name: "capacity",
            type: "number",
            label: "Kapasite",
            validations: { required: true },
          },
          {
            id: "a5",
            name: "level",
            type: "string",
            label: "Seviye",
            validations: { required: true },
          },
          {
            id: "a6",
            name: "duration",
            type: "number",
            label: "Süre",
            validations: { required: true },
          },
          {
            id: "a7",
            name: "trainer",
            type: "reference",
            label: "Eğitmen",
            validations: { required: true },
          },
          {
            id: "a8",
            name: "startDate",
            type: "date",
            label: "Başlangıç",
            validations: { required: true },
          },
          {
            id: "a9",
            name: "endDate",
            type: "date",
            label: "Bitiş",
            validations: { required: true },
          },
          {
            id: "a10",
            name: "status",
            type: "string",
            label: "Durum",
            validations: { required: true },
          },
          {
            id: "a11",
            name: "notes",
            type: "string",
            label: "Notlar",
            validations: { required: false },
          },
        ],
      },
    },
    {
      id: "participant",
      position: { x: 900, y: 400 },
      type: VersionType.MODEL,
      data: {
        name: "Participant",
        description: "Katılımcı bilgilerini içeren şema",
        isActive: true,
        fields: [
          {
            id: "p2",
            name: "customer",
            type: "reference",
            label: "Müşteri",
            validations: { required: true },
          },
          {
            id: "p3",
            name: "activity",
            type: "reference",
            label: "Aktivite",
            validations: { required: true },
          },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "membership",
      target: "customer",
      animated: true,
      label: "N:1",
      type: VersionType.MODEL,
      data: { type: "oneToMany" },
    },
    {
      id: "e2",
      source: "membership",
      target: "membershipType",
      animated: true,
      label: "N:1",
      type: VersionType.MODEL,
      data: { type: "oneToMany" },
    },
    {
      id: "e3",
      source: "participant",
      target: "customer",
      animated: true,
      label: "N:1",
      type: VersionType.MODEL,
      data: { type: "oneToMany" },
    },
    {
      id: "e4",
      source: "activity",
      target: "trainer",
      animated: true,
      label: "N:1",
      type: VersionType.MODEL,
      data: { type: "oneToMany" },
    },
    {
      id: "e5",
      source: "customer",
      target: "user",
      animated: true,
      label: "N:1",
      type: VersionType.MODEL,
      data: { type: "oneToMany" },
    },
    {
      id: "e6",
      source: "participant",
      target: "activity",
      animated: true,
      label: "N:1",
      type: VersionType.MODEL,
      data: { type: "oneToMany" },
    },
  ],
};
