import { IVersion } from "@/lib/models/version";

export const matrixModel: IVersion = {
  id: "matrixModel",
  name: "Matrix",
  description: "Matrix Model",
  is_active: false,
  type: "model",
  nodes: [
    {
      id: "User",
      position: { x: 100, y: 100 },
      data: [
        {
          id: "n2",
          name: "fullname",
          type: "string",
          label: "Full Name",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "email",
          type: "string",
          label: "Email",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "password",
          type: "string",
          label: "Password",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "role",
          type: "string",
          label: "Role",
          validations: { required: true },
        },
        {
          id: "n6",
          name: "photo",
          type: "string",
          label: "Photo",
          validations: { required: false },
        },
      ],
    },
    {
      id: "Project",
      position: { x: 500, y: 100 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "n3",
          name: "user",
          type: "reference",
          label: "User",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Version",
      position: { x: 100, y: 400 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "n3",
          name: "is_active",
          type: "boolean",
          label: "Is Active",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "type",
          type: "string",
          label: "Type",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "project",
          type: "reference",
          label: "Project",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Node",
      position: { x: 500, y: 400 },
      data: [
        {
          id: "n1",
          name: "version",
          type: "reference",
          label: "Version",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "data",
          type: "object",
          label: "Data",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "position",
          type: "object",
          label: "Position",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Edge",
      position: { x: 100, y: 800 },
      data: [
        {
          id: "n1",
          name: "source",
          type: "string",
          label: "Source",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "target",
          type: "string",
          label: "Target",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "animated",
          type: "boolean",
          label: "Animated",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "label",
          type: "string",
          label: "Label",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "data",
          type: "object",
          label: "Data",
          validations: { required: true },
        },
        {
          id: "n6",
          name: "version",
          type: "reference",
          label: "Version",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Screen",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "n3",
          name: "props",
          type: "object",
          label: "Props",
          validations: { required: false },
        },
        {
          id: "n4",
          name: "project",
          type: "reference",
          label: "Project",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Page",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
        {
          id: "n3",
          name: "props",
          type: "object",
          label: "Props",
          validations: { required: false },
        },
        {
          id: "n4",
          name: "project",
          type: "reference",
          label: "Project",
          validations: { required: true },
        },
      ],
    },

    {
      id: "Agent",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "instructions",
          type: "string",
          label: "Instructions",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "stream",
          type: "boolean",
          label: "Stream",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "model_provider",
          type: "string",
          label: "Model Provider",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "model_name",
          type: "string",
          label: "Model Name",
          validations: { required: true },
        },
        {
          id: "n6",
          name: "key",
          type: "reference",
          label: "Key",
          validations: { required: true },
        },
        {
          id: "n7",
          name: "photo",
          type: "string",
          label: "Photo",
          validations: { required: false },
        },
        {
          id: "n8",
          name: "is_public",
          type: "boolean",
          label: "Is Public",
          validations: { required: true },
        },
        {
          id: "n9",
          name: "title",
          type: "string",
          label: "Title",
          validations: { required: false },
        },
        {
          id: "n10",
          name: "seed",
          type: "number",
          label: "Seed",
          validations: { required: true },
        },
        {
          id: "n11",
          name: "max_tokens",
          type: "number",
          label: "Max Tokens",
          validations: { required: true },
        },
        {
          id: "n12",
          name: "temperature",
          type: "number",
          label: "Temperature",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Key",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "value",
          type: "string",
          label: "Value",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "type",
          type: "string",
          label: "Type",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "user",
          type: "reference",
          label: "User",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
      ],
    },
    {
      id: "Hiring",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "user",
          type: "reference",
          label: "User",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "agent",
          type: "reference",
          label: "Agent",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Chat",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "role",
          type: "string",
          label: "Role",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "content",
          type: "string",
          label: "Content",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "session",
          type: "reference",
          label: "Session",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "attachments",
          type: "array",
          label: "Attachments",
          validations: { required: false },
        },
      ],
    },
    {
      id: "Session",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "agent",
          type: "reference",
          label: "Agent",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "user",
          type: "reference",
          label: "User",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Family",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "agent",
          type: "reference",
          label: "Agent",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "parent",
          type: "reference",
          label: "Parent",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "order",
          type: "number",
          label: "Order",
          validations: { required: true },
        },
      ],
    },
    {
      id: "Model",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "project",
          type: "reference",
          label: "Project",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "description",
          type: "string",
          label: "Description",
          validations: { required: false },
        },
      ],
    },
    {
      id: "Field",
      position: { x: 500, y: 800 },
      data: [
        {
          id: "n1",
          name: "name",
          type: "string",
          label: "Name",
          validations: { required: true },
        },
        {
          id: "n2",
          name: "model",
          type: "reference",
          label: "Model",
          validations: { required: true },
        },
        {
          id: "n3",
          name: "label",
          type: "string",
          label: "Label",
          validations: { required: true },
        },
        {
          id: "n4",
          name: "type",
          type: "string",
          label: "Type",
          validations: { required: true },
        },
        {
          id: "n5",
          name: "validations",
          type: "object",
          label: "Validations",
          validations: { required: false },
        },
      ],
    },
  ],
  edges: [
    {
      id: "e1",
      source: "Key",
      target: "Agent",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e2",
      source: "Session",
      target: "Chat",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e3",
      source: "Version",
      target: "Edge",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e4",
      source: "Family",
      target: "Agent",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e5",
      source: "Model",
      target: "Field",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e6",
      source: "Project",
      target: "Flow",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e7",
      source: "Flow",
      target: "FlowSession",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e8",
      source: "Session",
      target: "FlowSession",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e9",
      source: "Agent",
      target: "FlowStep",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e10",
      source: "Flow",
      target: "FlowStep",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e11",
      source: "User",
      target: "Hiring",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e12",
      source: "Agent",
      target: "Hiring",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e13",
      source: "User",
      target: "Key",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e14",
      source: "Project",
      target: "Model",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e15",
      source: "Version",
      target: "Node",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e16",
      source: "Project",
      target: "Page",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e17",
      source: "User",
      target: "Project",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e18",
      source: "Project",
      target: "Screen",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e19",
      source: "Agent",
      target: "Session",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e20",
      source: "User",
      target: "Session",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
    {
      id: "e21",
      source: "Project",
      target: "Version",
      animated: true,
      label: "N:1",
      data: {
        relationType: "oneToMany",
      },
    },
  ],
};
